# setups

In [1]:
import numpy as np
print(np.__version__)

2.0.2


In [2]:
np?

Type:        module
String form: <module 'numpy' from 'c:\\Users\\LENOVO\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\numpy\\__init__.py'>
File:        c:\users\lenovo\appdata\local\programs\python\python39\lib\site-packages\numpy\__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets

# arrays
Unlike python lists, NumPy is constrained to arrays that contain the same type.

In [3]:
np.array([1, 2, 3])

array([1, 2, 3])

array automatically upcast objects to the same data type

In [4]:
np.array([True,1,2,3])


array([1, 1, 2, 3])

## explanation: why numpy?
NumPy arrays are faster than Python lists mainly because:

- They store homogeneous data types

- Data are stored in contiguous memory

- They avoid Python object overhead

- Computation is performed in optimized C/Fortran code

In [5]:
print(np.ones((3,4),dtype=str))
print(np.full((3,3),3.14))
print(np.arange(0,10,2))
print(np.linspace(0,10,5,dtype=int))# contains both start and end
print(np.random.random((3,3)))
np.empty(3)

[['1' '1' '1' '1']
 ['1' '1' '1' '1']
 ['1' '1' '1' '1']]
[[3.14 3.14 3.14]
 [3.14 3.14 3.14]
 [3.14 3.14 3.14]]
[0 2 4 6 8]
[ 0  2  5  7 10]
[[0.6396038  0.6755117  0.61423479]
 [0.21727948 0.56387941 0.24066072]
 [0.09300596 0.36222529 0.48424007]]


array([2.49399082e-306, 1.63400525e-301, 9.16713724e-278])

``` np.empty() ``` allocates memory for an array without initializing its values. The elements therefore contain arbitrary data already present in memory. It is mainly used for performance when the array will be immediately filled with new values. It's faster than generating other fillers.

In [6]:
print(np.full((3,4),fill_value=True,dtype=np.int_))

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [7]:
x1=np.random.randint(10,size=6)
x1

array([5, 1, 0, 9, 2, 4], dtype=int32)

In [8]:
x3=np.array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [0, 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])
x3[:,0,:2]

array([[1., 1.],
       [0., 0.],
       [1., 1.]])

In [9]:
x=np.arange(2,10,2)
np.concatenate([x,x,x]).reshape(3,4)


array([[2, 4, 6, 8],
       [2, 4, 6, 8],
       [2, 4, 6, 8]])

In [10]:
x=np.eye(2)
np.stack([x, x],axis=2)

array([[[1., 1.],
        [0., 0.]],

       [[0., 0.],
        [1., 1.]]])

# explore UFuncs !!

In [13]:
np.power(2,3)
x=np.linspace(0,np.pi,5)
print(np.sin(x))
print(np.power(x,2))

[0.00000000e+00 7.07106781e-01 1.00000000e+00 7.07106781e-01
 1.22464680e-16]
[0.         0.61685028 2.4674011  5.55165248 9.8696044 ]


In [18]:
from scipy import special
x = [1, 5, 10]
print("gamma(x) =", special.gamma(x))
print("ln|gamma(x)| =", special.gammaln(x))
print("beta(x, 2) =", special.beta(x, 2))

gamma(x) = [1.0000e+00 2.4000e+01 3.6288e+05]
ln|gamma(x)| = [ 0.          3.17805383 12.80182748]
beta(x, 2) = [0.5        0.03333333 0.00909091]


In [20]:
x=np.array([1,2,3])
y=np.array([4,5,6])
np.power(x,2,out=y[0:3])

array([1, 4, 9])

In [26]:
x=np.arange(1,6)
y=np.arange(1,5)
np.multiply.outer(y,x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20]])

In [28]:
np.arange(3).reshape((3,1))
np.arange(3)[:,np.newaxis]

array([[0],
       [1],
       [2]])

In [33]:
x=np.array([1, 2, 3])
y=np.array([1,1])[:,np.newaxis]
x+y

array([[2, 3, 4],
       [2, 3, 4]])

In [37]:
x=np.array([1,2,3])
y=x.reshape((3,1))
np.multiply(y,x)

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [42]:
x=np.arange(10)
# np.count_nonzero(x<5)
print(x<5)
print(np.sum(x<5))
print(np.all(x<10))

[ True  True  True  True  True False False False False False]
5
True
