In [3]:
import numpy as np
data=np.loadtxt("lab_data.txt",delimiter=' ')
print(data)
X=data[:,:-1]
y=data[:,-1]
print(X,y)
print(y.shape)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]
[[1. 2. 3.]
 [5. 6. 7.]] [4. 8.]
(2,)


In [7]:
w=[1,1,1]
b=1
print(X@w)

[ 6. 18.]


X@w=[6;18]
+b=[7;19]
-y=[3,15]
*=